import copy
import re
from pathlib import Path

import pytest
import yaml

from publishable.diagnostics import Collector
from publishable.errors import ContractError
from publishable.materialize import materialize_config
from publishable.param import Param
from publishable.replication import resolve_repeats
from publishable.templates.base import BaseTemplate
from publishable.templates.registry import get_template
from publishable.validate import validate_config


class _OneParamTemplate(BaseTemplate):
    def __init__(self, default: str) -> None:
        self.parameter_spec = {"analysis.value": Param(str, default=default)}


def rendered() -> str:
    return materialize_config(
        template=get_template("generic"),
        template_name="generic",
        name="cohort-pilot",
        input_dir="/secure/data/cohort-2026",
        output_dir="/secure/results/cohort-pilot",
        entrypoint="cohort_pilot.experiment:CohortPilotExperiment",
    )


def test_every_parameter_is_materialized_with_its_default():
    doc = yaml.safe_load(rendered())
    assert doc["parameters"]["analysis"] == {
        "method": "pearson",
        "min_samples": 30,
        "confidence": 0.95,
        "drop_missing": True,
    }


def test_the_four_identifying_fields_are_present():
    doc = yaml.safe_load(rendered())
    assert doc["schema_version"] == "1.0"
    assert doc["experiment_type"] == "generic"
    assert doc["template_version"] == "1.0.0"
    assert doc["plugin"] is None


def test_a_local_template_carries_no_core_template_version(tmp_path: Path):
    """`materialize_config` writes `template_version` from core's own module
    constant — meaningless for a template core did not write (`docs/
    reference.md` § Three hashes). So a config generated against a project-
    local template must carry no `template_version` key at all, and the header
    comment's ``v{TEMPLATE_VERSION}`` clause must be dropped with it, since
    that clause is the same false claim in prose.

    THE CONTROL: `generic`, rendered from the same helper in the same test,
    still gets both the key and the header version — a change that dropped
    `template_version` for every template would pass the local half and fail
    the control.

    `plugin: null` is pinned here too: decision 2 makes no code change for it,
    only a test, since `null` already meant "no distributable source" and a
    local template has none either.
    """
    templates = tmp_path / "templates"
    templates.mkdir()
    (templates / "my_assay.py").write_text(
        "from publishable import BaseTemplate, register_template\n\n\n"
        '@register_template("my_assay")\n'
        "class MyAssay(BaseTemplate):\n"
        "    pass\n"
    )
    local = get_template("my_assay", tmp_path)
    assert local is not None
    text = materialize_config(
        template=local,
        template_name="my_assay",
        name="cohort-pilot",
        input_dir="/secure/data/cohort-2026",
        output_dir="/secure/results/cohort-pilot",
        entrypoint="cohort_pilot.experiment:CohortPilotExperiment",
    )
    doc = yaml.safe_load(text)
    assert "template_version" not in doc
    assert doc["plugin"] is None
    header = text.splitlines()[1]
    assert header == "# Generated by `publishable init` from template `my_assay`."

    control_doc = yaml.safe_load(rendered())
    assert control_doc["template_version"] == "1.0.0"
    control_header = rendered().splitlines()[1]
    assert control_header == ("# Generated by `publishable init` from template `generic` v1.0.0.")


def test_materialize_reports_the_class_version_not_the_core_constant():
    """`materialize_config` takes a template *instance*, exactly as
    `validate._check_versions` does, so the same non-local class whose
    `version` differs from `TEMPLATE_VERSION` pins this reader too — Row 212's
    false guarantee applies at both places `type(template).version` is read.

    `Versioned` is not under any repo's `templates/`, so `is_local_template`
    is False and `reported = type(template).version` is reached rather than
    the `local` branch `test_a_local_template_carries_no_core_template_version`
    already covers.
    """
    from publishable.materialize import TEMPLATE_VERSION

    class Versioned(BaseTemplate):
        version = "9.9.9"
        parameter_spec = {}

    text = materialize_config(
        template=Versioned(),
        template_name="versioned",
        name="cohort-pilot",
        input_dir="/secure/data/cohort-2026",
        output_dir="/secure/results/cohort-pilot",
        entrypoint="cohort_pilot.experiment:CohortPilotExperiment",
    )
    doc = yaml.safe_load(text)
    assert doc["template_version"] == "9.9.9"
    assert TEMPLATE_VERSION not in text
    header = text.splitlines()[1]
    assert header == "# Generated by `publishable init` from template `versioned` v9.9.9."


def test_a_template_class_defined_in_a_dunder_helper_is_still_local(tmp_path: Path):
    """`is_local_template` must not be fooled by `__module__` alone. `MyAssay`
    is *defined* in `templates/__helper.py` — a dunder-prefixed file
    `discover_local` never imports directly, so its `__module__` carries the
    helper's own real name rather than the `_publishable_local_*` synthetic
    one `_module_name` gives a directly-imported file — and only *registered*
    from `templates/my_assay.py`, the file discover_local does walk. A
    predicate reading the module-name prefix would call this class
    non-local and let core's `template_version` be written and compared
    against it: exactly the false claim this task removes. `discover_local`
    stamps the class itself as local at registration, regardless of where it
    was defined, so this must still carry no `template_version`.
    """
    templates = tmp_path / "templates"
    templates.mkdir()
    (templates / "__helper.py").write_text(
        "from publishable import BaseTemplate\n\n\nclass MyAssay(BaseTemplate):\n    pass\n"
    )
    (templates / "my_assay.py").write_text(
        "from publishable import register_template\n"
        "from __helper import MyAssay\n\n\n"
        'register_template("my_assay")(MyAssay)\n'
    )
    local = get_template("my_assay", tmp_path)
    assert local is not None
    assert type(local).__name__ == "MyAssay"
    text = materialize_config(
        template=local,
        template_name="my_assay",
        name="cohort-pilot",
        input_dir="/secure/data/cohort-2026",
        output_dir="/secure/results/cohort-pilot",
        entrypoint="cohort_pilot.experiment:CohortPilotExperiment",
    )
    doc = yaml.safe_load(text)
    assert "template_version" not in doc


def test_constraints_arrive_as_inline_comments():
    text = rendered()
    assert "# choices: pearson | spearman | kendall" in text
    assert "# integer >= 2" in text
    assert "# float in (0, 1)" in text


def test_limits_carry_the_documented_defaults():
    doc = yaml.safe_load(rendered())
    assert doc["limits"] == {
        "max_executions": 500,
        "max_failed_fraction": 0.2,
        "max_ineligible_fraction": 0.5,
        "min_units_per_cell": 20,
        "min_clusters": 10,
        "min_reported_n": 10,
    }


def test_the_generated_config_declares_a_unit_roster():
    doc = yaml.safe_load(rendered())
    units = doc["data"]["units"]
    assert units["from"] == "index.csv"
    assert units["key"] == "patient_id"
    assert units["attributes"] == []
    assert units["allocation"] == "within"
    for optional in ("cluster_by", "weight_by", "measurements", "holdout"):
        assert units[optional] is None, f"{optional} must be null, not absent or declared"


def test_the_generated_units_block_carries_its_comments():
    """The `from` enum lists every value § The one config file defines.

    All three values, unmarked: none is refused wholesale any more, so nothing
    here reads `(NOT BUILT)`. `_the_from_enum_s_not_built_marking_is_honoured_by_core`,
    which checked that marking against behaviour, is gone along with the marking —
    `tests/test_materialize.py`'s `_MARKED_LATER_SLICE` sweep is what would catch it
    resurfacing.
    """
    text = rendered()
    assert '# index.csv | {glob: "*.dcm"} | {resolver: <name>}' in text
    assert "# within | between" in text


_MARKED_LATER_SLICE = re.compile(
    r"#\s*(?P<live>[\w.]+)\s*\(\s*(?P<later>[^:]+):\s*later slice\s*\)"
)

# Where a marked field lives in the parsed doc, and how to ask core whether a
# given value there is refused. `kind` is only refused at `resolve_repeats` (it
# is not read by `validate_config` at all), so it gets its own probe.
# `allocation` was here until task 17 retired `E-DATA-ALLOCATION-UNSUPPORTED`:
# `between` is built and runs end to end, so `init`'s comment no longer marks
# it, and this dict no longer carries a path for it. `kind` left for the same
# reason at task 20: `replication.SUPPORTED_KINDS` is `seed`, `batch`, `fold`,
# all three built, so `init`'s `(fold: later slice)` was a marking core no
# longer honors — it now writes the enum § The one config file shows,
# `seed | batch | fold`. The registry is empty rather than deleted: the loop
# below still refuses a marking with no path registered here, which is what
# keeps the next one honest.
_MARKED_FIELD_PATHS: dict[str, tuple[object, ...]] = {}


def _refusal_codes(key: str, doc: dict, config_path: Path) -> list[str]:
    if key == "kind":
        try:
            resolve_repeats(doc, "digest")
        except ContractError as exc:
            return [exc.code]
        return []
    config_path.write_text(yaml.safe_dump(doc))
    c = Collector()
    validate_config(config_path, c)
    return [f.code for f in c.findings]


def test_no_enum_comment_names_a_value_validate_or_run_would_refuse(git_repo, tmp_path):
    """Every `(x: later slice)` marking must be honored by core, and the value

    `init` actually writes must never be one of the marked ones — a comment
    that lies in either direction sends a user into a refusal for nothing.
    """
    input_dir = tmp_path / "input"
    input_dir.mkdir()
    (input_dir / "index.csv").write_text("patient_id\np1\n")
    output_dir = tmp_path / "output"

    text = materialize_config(
        template=get_template("generic"),
        template_name="generic",
        name="cohort-pilot",
        input_dir=str(input_dir),
        output_dir=str(output_dir),
        entrypoint="cohort_pilot.experiment:CohortPilotExperiment",
    )
    base_doc = yaml.safe_load(text)
    base_doc["metadata"]["description"] = "a pilot"
    base_doc["metadata"]["authors"] = ["A"]

    config_path = git_repo / "configs" / "cohort-pilot" / "config.yaml"
    config_path.parent.mkdir(parents=True)

    # The config `init` actually writes must validate and run clean.
    assert _refusal_codes("allocation", base_doc, config_path) == []
    assert _refusal_codes("kind", base_doc, config_path) == []
    assert _refusal_codes("order", base_doc, config_path) == []

    marked_keys_seen = set()
    for line in text.splitlines():
        m = _MARKED_LATER_SLICE.search(line)
        if not m:
            continue
        pre = line.split("#")[0]
        key_match = re.search(r"(\w+):\s*\S", pre)
        assert key_match, f"could not find a key on the marked line: {line!r}"
        key = key_match.group(1)
        assert key in _MARKED_FIELD_PATHS, (
            f"`{key}` marks a value as a later slice but has no path registered in "
            f"this test — add one to _MARKED_FIELD_PATHS"
        )
        marked_keys_seen.add(key)
        path = _MARKED_FIELD_PATHS[key]
        for value in (v.strip() for v in m["later"].split(",")):
            doc = copy.deepcopy(base_doc)
            node = doc
            for step in path[:-1]:
                node = node[step]
            node[path[-1]] = value
            codes = _refusal_codes(key, doc, config_path)
            assert codes, (
                f"comment marks `{key}={value}` as refused later, but core accepted "
                f"it silently — the marking is stale (or the value is supported now, "
                f"and the comment should say so instead of hiding it)"
            )

    assert marked_keys_seen == set(_MARKED_FIELD_PATHS), (
        "expected a `(...: later slice)` marking for each of "
        f"{sorted(_MARKED_FIELD_PATHS)}; saw {sorted(marked_keys_seen)}"
    )


def test_replication_defaults_to_five_seed_repeats():
    doc = yaml.safe_load(rendered())
    assert doc["replication"]["repeats"] == [{"kind": "seed", "n": 5}]
    assert doc["replication"]["order"] == "as_declared"


def _rendered_with_default(default: str) -> str:
    return materialize_config(
        template=_OneParamTemplate(default),
        template_name="one-param",
        name="one-param-pilot",
        input_dir="/secure/data",
        output_dir="/secure/results",
        entrypoint="one_param.experiment:OneParamExperiment",
    )


def test_an_empty_string_default_round_trips_to_empty_string_not_null():
    doc = yaml.safe_load(_rendered_with_default(""))
    assert doc["parameters"]["analysis"]["value"] == ""


@pytest.mark.parametrize("default", ["yes", "null", "1.5"])
def test_yaml_lookalike_string_defaults_round_trip_as_strings(default: str):
    doc = yaml.safe_load(_rendered_with_default(default))
    value = doc["parameters"]["analysis"]["value"]
    assert value == default
    assert isinstance(value, str)


def test_a_default_containing_colon_space_still_parses_intact():
    doc = yaml.safe_load(_rendered_with_default("ratio: 1"))
    assert doc["parameters"]["analysis"]["value"] == "ratio: 1"


class _KeysTemplate(BaseTemplate):
    def __init__(self, *paths: str) -> None:
        self.parameter_spec = {path: Param(int, default=1) for path in paths}


def _rendered_with_keys(*paths: str) -> str:
    return materialize_config(
        template=_KeysTemplate(*paths),
        template_name="keys",
        name="keys-pilot",
        input_dir="/secure/data",
        output_dir="/secure/results",
        entrypoint="keys.experiment:KeysExperiment",
    )


def test_bool_and_null_lookalike_keys_round_trip_as_strings():
    doc = yaml.safe_load(_rendered_with_keys("t.yes", "t.null"))
    keys = list(doc["parameters"]["t"])
    assert set(keys) == {"yes", "null"}
    for key in keys:
        assert type(key) is str


def test_a_number_lookalike_key_round_trips_as_a_string():
    doc = yaml.safe_load(_rendered_with_keys("t.2024"))
    (key,) = doc["parameters"]["t"]
    assert key == "2024"
    assert type(key) is str


def test_generic_method_value_emits_bare_matching_the_specification():
    text = rendered()
    assert "method: pearson" in text
    assert 'method: "pearson"' not in text


def test_generic_non_string_values_emit_bare():
    text = rendered()
    assert "min_samples: 30" in text
    assert "confidence: 0.95" in text
    assert "drop_missing: true" in text


def test_generic_keys_that_need_no_quoting_still_emit_bare():
    text = rendered()
    assert "  analysis:" in text
    assert any(line.strip().startswith("method:") for line in text.splitlines()), (
        'method: must render bare, not "method":'
    )


def test_a_non_two_segment_parameter_path_fails_loudly():
    """`BaseTemplate.__init_subclass__` (`E-TEMPLATE-PARAM-PATH`,
    `tests/test_templates.py`) now rejects a malformed path the moment a
    template *class* declaring it as a class attribute is defined — well
    before `materialize_config` or any instance can exist — so
    `_parameters_block`'s own `ValueError` is unreachable through a
    class-attribute `parameter_spec` (every template `reference.md` shows)
    and is exercised here directly instead, against a hand-built `dict` no
    class ever has to carry. It is NOT unreachable in general: `_OneParamTemplate`
    above assigns `self.parameter_spec` inside `__init__`, an instance
    attribute `__init_subclass__` never sees, and still reaches this same
    guard the old way — see `_parameters_block`'s own docstring for that
    residual."""
    from publishable.materialize import _parameters_block

    with pytest.raises(ValueError, match="threshold"):
        _parameters_block({"threshold": Param(int, default=1)})


def test_the_plugin_field_carries_what_generate_was_told(tmp_path: Path):
    """`plugin` is a readable note beside the authoritative pin in `uv.lock`
    rather than a second one — so it records the argument verbatim, including a
    version suffix, and core never installs from the field itself."""
    text = materialize_config(
        template=get_template("generic"),
        template_name="generic",
        name="cohort-pilot",
        input_dir=str(tmp_path / "in"),
        output_dir=str(tmp_path / "out"),
        entrypoint="cohort_pilot.experiment:CohortPilotExperiment",
        plugin="someuser/publishable-llm@v1.2.0",
    )
    assert yaml.safe_load(text)["plugin"] == "someuser/publishable-llm@v1.2.0"

    # THE CONTROL, and the regression: with no plugin the field is `null`, which
    # is what every other test in this file's generated config asserts.
    plain = materialize_config(
        template=get_template("generic"),
        template_name="generic",
        name="cohort-pilot",
        input_dir=str(tmp_path / "in"),
        output_dir=str(tmp_path / "out"),
        entrypoint="cohort_pilot.experiment:CohortPilotExperiment",
    )
    assert yaml.safe_load(plain)["plugin"] is None


def test_the_plugin_field_stays_a_string_even_when_it_looks_like_a_mapping(tmp_path: Path):
    """Review M3: an un-quoted `plugin: {a: b}` re-parses as a YAML mapping
    rather than the string it was written to record verbatim. A `--plugin`
    value is a creation-time flag the author types, so it must round-trip as
    text — not be reinterpreted by the format it happens to land in."""
    text = materialize_config(
        template=get_template("generic"),
        template_name="generic",
        name="cohort-pilot",
        input_dir=str(tmp_path / "in"),
        output_dir=str(tmp_path / "out"),
        entrypoint="cohort_pilot.experiment:CohortPilotExperiment",
        plugin="{a: b}",
    )
    assert yaml.safe_load(text)["plugin"] == "{a: b}"


# ---------------------------------------------------------------------------
# W5 — a required parameter's rendered line. `docs/superpowers/W5-SCOPING.md`.
# ---------------------------------------------------------------------------


class _RequiredTemplate(BaseTemplate):
    """One required `Param` of every type, plus a defaulted one as the control."""

    parameter_spec = {
        "a.req_str": Param(str, help="Instrument model identifier"),
        "a.req_int": Param(int, ge=2),
        "a.req_float": Param(float),
        "a.req_bool": Param(bool),
        "a.req_list": Param(list, item_type=str),
        "a.req_nullable": Param(str, nullable=True),
        "a.optional": Param(int, default=7),
    }


def _required_lines() -> dict[str, str]:
    text = materialize_config(
        template=_RequiredTemplate(),
        template_name="generic",
        name="cohort-pilot",
        input_dir="/secure/data/cohort-2026",
        output_dir="/secure/results/cohort-pilot",
        entrypoint="cohort_pilot.experiment:CohortPilotExperiment",
    )
    return {
        line.strip().split(":")[0]: line
        for line in text.split("\n")
        if line.startswith("    ") and ("req_" in line or "optional" in line)
    }


def test_w5_every_required_parameter_is_marked_and_carries_no_value():
    """§ Templates promises the marker `metadata.description` gets. It described one
    `init` did not write, in a table, a paragraph and a consequence.

    The value stays **absent** rather than becoming its type's empty value: the key
    then parses as `null`, which is what `validate` refuses, and `0`/`false`/`[]`
    stay declarable for a required parameter of those types.
    """
    lines = _required_lines()
    # The pad is what `_parameters_block` computes to column 36; asserted as the
    # whole line rather than as a substring, because the trailing-space arm below
    # depends on this padding being what absorbs the empty value.
    assert lines["req_str"] == (
        "    req_str:" + " " * 24 + "# REQUIRED — Instrument model identifier"
    )
    assert lines["req_int"].endswith("# REQUIRED — integer >= 2")
    assert lines["req_list"].endswith("# REQUIRED — list of string")
    assert lines["req_float"].endswith("# REQUIRED")
    assert lines["req_bool"].endswith("# REQUIRED")
    for name in ("req_str", "req_int", "req_float", "req_bool", "req_list"):
        assert yaml.safe_load(lines[name].split("#")[0].strip()) == {name: None}


def test_w5_a_defaulted_parameter_line_is_unchanged():
    """The control that stops the marker leaking onto every line — without it the
    arm above passes against a materializer that prefixes everything."""
    line = _required_lines()["optional"]
    assert line.strip() == "optional: 7"
    assert "REQUIRED" not in line


def test_w5_a_required_line_carries_no_trailing_whitespace():
    """It did, in exactly the case nothing supplied a comment: the empty value left
    `    req_float: ` with a space, in generated YAML that lands in a user's
    repository. The marker is always a comment, so the pad absorbs it."""
    for name, line in _required_lines().items():
        assert line == line.rstrip(), f"{name}: {line!r}"


def test_w5_the_marker_is_the_only_signal_when_null_is_legal(tmp_path: Path, monkeypatch):
    """`Param(str, nullable=True)` with no default is required **and** accepts null,
    so the key `init` leaves unfilled validates clean — measured, and no refusal can
    catch it, because null is a value the parameter legally takes.

    That is why this slice added a marker rather than a rule: for this one
    declaration the comment is the only thing that can tell a reader anything.
    """
    lines = _required_lines()
    assert lines["req_nullable"].endswith("# REQUIRED")
    assert Param(str, nullable=True).check(None) is None
