"""parameter_spec → the one config file. docs/reference.md § The one config file."""

from typing import Any

from publishable.param import MISSING, Param
from publishable.templates.base import BaseTemplate

TEMPLATE_VERSION = "1.0.0"
INIT_REPEATS = 5  # what `init` writes; `default_repeats` is the warning floor


def _scalar(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return value
    return repr(value)


def _parameters_block(spec: dict[str, Param]) -> list[str]:
    """Render dotted paths as nested YAML with each Param's comment.

    Assumes every path has exactly two dotted segments — `generic` does. A
    one-segment or three-segment path would emit broken YAML, so we fail
    loudly instead of guessing at general nesting.
    """
    tree: dict[str, Any] = {}
    for path, param in spec.items():
        if path.count(".") != 1:
            raise ValueError(
                f"_parameters_block only supports two-segment dotted paths "
                f"(head.leaf); got {path!r}"
            )
        head, _, leaf = path.rpartition(".")
        tree.setdefault(head, {})[leaf] = param
    lines: list[str] = []
    for head, leaves in tree.items():
        lines.append(f"  {head}:")
        for leaf, param in leaves.items():
            value = "" if param.default is MISSING else _scalar(param.default)
            entry = f"    {leaf}: {value}"
            comment = param.comment()
            if comment:
                pad = " " * max(1, 36 - len(entry))
                entry = f"{entry}{pad}# {comment}"
            lines.append(entry)
    return lines


def materialize_config(
    *,
    template: BaseTemplate,
    template_name: str,
    name: str,
    input_dir: str,
    output_dir: str,
    entrypoint: str,
) -> str:
    body = [
        f"# configs/{name}/config.yaml",
        f"# Generated by `publishable init` from template `{template_name}` "
        f"v{TEMPLATE_VERSION}.",
        "# This file is the complete parameter set. Edit it, validate it, run it.",
        "",
        'schema_version: "1.0"',
        f"experiment_type: {template_name}",
        f'template_version: "{TEMPLATE_VERSION}"',
        "plugin: null",
        "",
        "metadata:",
        f"  name: {name}",
        '  description: ""                  # REQUIRED — one line, what this run is for',
        "  authors: []                      # REQUIRED",
        '  institution: ""',
        "",
        f'entrypoint: "{entrypoint}"',
        "",
        "data:",
        f"  input_dir: {input_dir}          # must be OUTSIDE the repo — enforced",
        f"  output_dir: {output_dir}",
        "  input_manifest_policy: hash_all  # hash_all | hash_index | none",
        "",
        "parameters:",
        "  # ---- Base values. Everything below is defined by the template, not by core. ----",
        *_parameters_block(template.parameter_spec),
        "",
        "replication:",
        "  repeats:",
        f"    - {{kind: seed, n: {INIT_REPEATS}}}          # seed | batch | fold",
        "  order: as_declared               # as_declared | randomized",
        '  rationale: ""',
        "",
        "statistics:",
        "  correction: holm                 # none | bonferroni | holm | fdr_bh",
        "",
        "limits:",
        "  max_executions: 500",
        "  max_failed_fraction: 0.2",
        "  max_ineligible_fraction: 0.5",
        "  min_units_per_cell: 20",
        "  min_clusters: 10",
        "  min_reported_n: 10",
        "",
        "hypotheses: []",
        "",
    ]
    return "\n".join(body)
