"""parameter_spec → the one config file. docs/reference.md § The one config file."""

from typing import Any

from publishable.param import MISSING, Param
from publishable.templates.base import BaseTemplate
from publishable.templates.discovery import is_local_template

TEMPLATE_VERSION = "1.0.0"
INIT_REPEATS = 5  # what `init` writes; `default_repeats` is the warning floor

# YAML 1.1 booleans/null that would swallow an otherwise-plain scalar if left bare.
_YAML_BARE_WORDS = {
    "y",
    "n",
    "yes",
    "no",
    "true",
    "false",
    "on",
    "off",
    "null",
    "~",
    "",
}


def _quote(s: str) -> str:
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _needs_quoting(s: str) -> bool:
    """Would `s`, written bare, fail to re-parse back to the string `s`?"""
    if s.strip() != s:
        return True
    if s.lower() in _YAML_BARE_WORDS:
        return True
    try:
        float(s)
    except ValueError:
        pass
    else:
        return True
    if s[:1] in "!&*-?:,[]{}#|>'\"%@`":
        return True
    return ": " in s or s.endswith(":") or "#" in s


def _key(name: str) -> str:
    return _quote(name) if _needs_quoting(name) else name


def _scalar(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return _quote(value) if _needs_quoting(value) else value
    return repr(value)


def _parameters_block(spec: dict[str, Param]) -> list[str]:
    """Render dotted paths as nested YAML with each Param's comment.

    Assumes every path has exactly two dotted segments — `generic` does. A
    one-segment or three-segment path would emit broken YAML, so we fail
    loudly instead of guessing at general nesting.
    """
    tree: dict[str, Any] = {}
    for path, param in spec.items():
        if path.count(".") != 1:
            raise ValueError(
                f"_parameters_block only supports two-segment dotted paths "
                f"(head.leaf); got {path!r}"
            )
        head, _, leaf = path.rpartition(".")
        tree.setdefault(head, {})[leaf] = param
    lines: list[str] = []
    for head, leaves in tree.items():
        lines.append(f"  {_key(head)}:")
        for leaf, param in leaves.items():
            value = "" if param.default is MISSING else _scalar(param.default)
            entry = f"    {_key(leaf)}: {value}"
            comment = param.comment()
            if comment:
                pad = " " * max(1, 36 - len(entry))
                entry = f"{entry}{pad}# {comment}"
            lines.append(entry)
    return lines


def materialize_config(
    *,
    template: BaseTemplate,
    template_name: str,
    name: str,
    input_dir: str,
    output_dir: str,
    entrypoint: str,
) -> str:
    local = is_local_template(type(template))
    reported = None if local else type(template).version
    header_version = "" if reported is None else f" v{reported}"
    body = [
        f"# configs/{name}/config.yaml",
        f"# Generated by `publishable init` from template `{template_name}`{header_version}.",
        "# This file is the complete parameter set. Edit it, validate it, run it.",
        "",
        'schema_version: "1.0"',
        f"experiment_type: {template_name}",
        *([] if reported is None else [f'template_version: "{reported}"']),
        "plugin: null",
        "",
        "metadata:",
        f"  name: {name}",
        '  description: ""                  # REQUIRED — one line, what this run is for',
        "  authors: []                      # REQUIRED",
        '  institution: ""',
        "",
        f'entrypoint: "{entrypoint}"',
        "",
        "data:",
        f"  input_dir: {input_dir}          # must be OUTSIDE the repo — enforced",
        f"  output_dir: {output_dir}",
        "  input_manifest_policy: hash_all  # hash_all | hash_index | none",
        "  units:",
        '    from: index.csv                # index.csv | {glob: "*.dcm"} '
        "| {resolver: <name>} (NOT BUILT)",
        "    key: patient_id                # stable, unique identity",
        "    attributes: []                 # available for stratification and reporting",
        "    allocation: within             # within | between",
        "    cluster_by: null               # e.g. site, when units aren't independent",
        "    weight_by: null                # e.g. sampling_weight, when the sample is enriched",
        "    measurements: null             # e.g. {by: read_id, collapse: mean}",
        "    holdout: null                  # e.g. {method: random, frac: 0.2}"
        " — one fixed train/test split",
        "",
        "parameters:",
        "  # ---- Base values. Everything below is defined by the template, not by core. ----",
        *_parameters_block(template.parameter_spec),
        "",
        "sweep: {}",
        "  # ---- What varies across conditions. Empty (or omitted) means a single,",
        "  #      unswept condition — no `conditions/` level in the run's artifact",
        "  #      tree. A parameter mode's keys are dotted paths into `parameters`;",
        "  #      the modes are grid | paired | sample | groups | baseline | ablate.",
        '  #      See "Sweeps and repeats" in reference.md.',
        "  # baseline: {analysis.method: pearson}   # optional reference condition",
        "  # grid:",
        "  #   analysis.method: [spearman, kendall]",
        "",
        "replication:",
        "  repeats:",
        f"    - {{kind: seed, n: {INIT_REPEATS}}}          # seed | batch | fold",
        "  order: as_declared               # as_declared | randomized",
        '  rationale: ""',
        "",
        "statistics:",
        "  correction: holm                 # none | bonferroni | holm | fdr_bh",
        "",
        "limits:",
        "  max_executions: 500",
        "  max_failed_fraction: 0.2",
        "  max_ineligible_fraction: 0.5",
        "  min_units_per_cell: 20",
        "  min_clusters: 10",
        "  min_reported_n: 10",
        "",
        "hypotheses: []",
        "",
    ]
    return "\n".join(body)
